version: "2"

services:
  api:
    build: ./back-end/
    ports:
      - "3001:3001"
    networks:
      mso_rooms:
        ipv4_address: 10.20.0.3
    container_name: mso-room-api

  client:
    build: ./front-end/
    ports:
      - "3000:3000"
    networks:
      mso_rooms:
        ipv4_address: 10.20.0.4
    depends_on:
      - api
    container_name: mso-rooms-front-end

networks:
  mso_rooms:
    external: true
    name: mso_rooms
