version: "2"

services:
  api:
    build: ./back-end/
    ports:
      - "3001:3001"
    depends_on:
      - db
    container_name: mso-room-api

  client:
    build: ./front-end/
    ports:
      - "3000:3000"
    depends_on:
      - api
    container_name: mso-rooms-front-end

  db:
    image: mongo:bionic
    ports:
      - "27017:27017"
    container_name: mso-rooms-database
